name: CI
on:
  push:
    branches:
      - develop

jobs:
  deploy-to-firebase:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle Wrapper
        run: gradle wrapper

      - name: Assemble Beta APK
        run: bash ./gradlew assembleBeta --stacktrace

      - name: Distribute to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: ${{secrets.FIREBASE_TESTER_GROUP}}
          file: app/build/outputs/apk/beta/app-beta.apk